import type { Metadata } from "next";
import "./globals.css";
import { Hanken_Grotesk } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { CartProvider } from "./context/CartContext";

const swiggyFont = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-swiggy",
});

export const metadata: Metadata = {
  title: "Swiggy Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${swiggyFont.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-sans">
        <CartProvider>
          <Navbar />
          {children}
          <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
